---
version: "2.2"
services:
    bot:
        build:
            context: .
            network: host
        image: scrimsbot:latest
        container_name: scrims-bot
        restart: always
        network_mode: host
        volumes:
            - "/apps/PugsBot/logs:/apps/PugsBot/logs"
